apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dev-machine
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dev-machine
        version: v1
    spec:
      containers:
      - name: dev-machine
        image: svarcoe/dev
        imagePullPolicy: Always
        
